#!/bin/bash

# REQUIRES: hubot with extension "hubot-script-shellcmd"
# add this script to node_modules/hubot-script-shellcmd/bash/handlers
#
# usage: botname shellcmd nmap ip


function valid_ip()
{
    local  ip="$1"
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if valid_ip "$1"; then /usr/bin/nmap -T4 -A -v "$1";  else echo please use ip address only ; fi


